### ISSUE TITLE
"x86_64-w64-mingw32-gcc": executable file not found

### ISSUE THREAD

**Issue by nicrodriquez** [michaelabon/streamdeck-logitech-litra-lights#22]
Here is the issue I am running into.. 

```
CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -C go  -o ../ca.michaelabon.logitech-litra-lights.sdPlugin/build/streamdeck-logitech-litra-lights.exe .
# runtime/cgo
cgo: C compiler "x86_64-w64-mingw32-gcc" not found: exec: "x86_64-w64-mingw32-gcc": executable file not found in $PATH
error: Recipe `build` failed on line 17 with exit code 1
nicrodriquez@Nics-MBP-1352 streamdeck-logitech-litra-lights % 
```

**Comment by michaelabon** [comment]
Hey @nicrodriquez! You didn't do anything wrong. That error message indicates that you need to install the Windows cross-compiling tool.

I'm pretty sure that you can do so with `brew install mingw-w64`.

That should be (but is not yet) part of the setup instructions (either docs or the Justfile). **If you can confirm that this works,** then I'll make the update to the Justfile.

**Comment by michaelabon** [comment]
@nicrodriquez I can confirm on my own that `mingw-w64` is the correct package. I've updated the `just install` command on `macos` to install that automatically. You can pull and try to re-build again.

**Comment by nicrodriquez** [comment]
thanks @michaelabon it is installed now, there were some weird hoops to hop around, but I got it. However now the plugin is installed yet when I try and use either of the options, a hazard icon appears on the stream deck for both the OFF and Temperature buttons.
